name: ansible
inputs:
    playbook:
        required: false  #if not copy from dockerfile need set true  
        default: optimize-sysctl.yml
    inventory:
        required: false
        default: localhost
runs:
    using: "docker"
    image: 'Dockerfile'
    args:
        - ${{ inputs.playbook }}
        - ${{ inputs.inventory }}
