name: Build Infrastructure


on:
  push:
    branches:
      - tri
  pull_request:
    branches:
      - tri

jobs:
  packer-build:
    #runs-on: ubuntu-latest  # Can be changed based on your needs
    runs-on: self-hosted

    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
      # volumes:
      #   - ansible:/ansible
      #   - packer:/packer
      #   - terraform:/terraform
      #   - vagrant:/vagrant

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: run git clone
        run: |
          ls -al
          cd ansible-optimize
          git checkout tri
          git clone https://github.com/CDN-Z/ansible-optimize.git
          git fetch --all
          git checkout tri

      - name: Set up Docker Build Environment
        run: |
          echo "Setting up Docker environment for Packer build"

      - name: Run Packer Build
        uses: ./.github/actions  # Reference custom action (Docker container)
        with:
          vcenter_user: ${{ secrets.VCENTER_USER }}
          vcenter_password: ${{ secrets.VCENTER_PASSWORD }}
          vcenter_server: ${{ secrets.VCENTER_SERVER }}
          
