name: deploy ansible

on:
  pull_request:
    branches: ["main", "stable", "release/v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: run-ansible-lint
        uses: ansible/ansible-lint@v25.2.1
        with:
          targets: ""

  deployAnsible:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ./.github/actions/ansible
        with: 
          playbook: playbook.yml
          inventory: localhost
