name: deploy ansible

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

#      - name: run-ansible-lint
#        uses: ansible/ansible-lint@v25.2.1

        with:
          targets: ".github/actions"
          setup_python: true

  deployAnsible:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions
        with:
          playbook: "optimize-sysctl.yml"
          inventory: localhost
